Repository ifpeopensource/merenda-server, pull requests merged in 2023-02, with the labels that each got.

#6 Envio de E-mail
  .env.template
  package-lock.json
  package.json
  src/server.js
  src/services/MailService.js
  src/utils/generateStudentQRCode.js
Labels: enhancement

#12 Resolve erro nos links
  README.md
Labels: bug

#10 Cria todos os endpoints para acesso ao banco de dados
  .env.template
  package-lock.json
  package.json
  prisma/migrations/20230216191821_base_migration/migration.sql
  prisma/migrations/20230216212259_/migration.sql
  prisma/migrations/20230218212450_user_student/migration.sql
  prisma/migrations/20230220052020_update_tables_names/migration.sql
  prisma/schema.prisma
  src/PrismaClient.js
  src/controllers/OauthController.js
  src/controllers/StudentController.js
  src/controllers/UserController.js
  src/errors/EntryExists.js
  src/errors/InvalidPassword.js
  src/middlewares/AuthMiddleware.js
  src/middlewares/RequireAdminMiddleware.js
  src/middlewares/RequireVerifierMiddleware.js
  src/routes.js
  src/routes/oauth.js
  src/routes/students.js
  src/routes/users.js
  src/server.js
  src/services/OauthService.js
  src/services/StudentService.js
  src/services/UserService.js
  src/utils/generateFormattedError.js
Labels: enhancement

#13 Cria documentação da API
  .eslintignore
  .prettierignore
  docs/index.html
  docs/swagger-ui.html
  docs/swagger-ui/index.css
  docs/swagger-ui/oauth2-redirect.html
  docs/swagger-ui/swagger-initializer.js
  docs/swagger-ui/swagger-ui-bundle.js
  docs/swagger-ui/swagger-ui-bundle.js.map
  docs/swagger-ui/swagger-ui-es-bundle-core.js
  docs/swagger-ui/swagger-ui-es-bundle-core.js.map
  docs/swagger-ui/swagger-ui-es-bundle.js
  docs/swagger-ui/swagger-ui-es-bundle.js.map
  docs/swagger-ui/swagger-ui-standalone-preset.js
  docs/swagger-ui/swagger-ui-standalone-preset.js.map
  docs/swagger-ui/swagger-ui.css
  docs/swagger-ui/swagger-ui.css.map
  docs/swagger-ui/swagger-ui.js
  docs/swagger-ui/swagger-ui.js.map
  docs/swagger.yaml
Labels: documentation

#21 docs: Cria temas
  docs/index.html
  docs/swagger.yaml
Labels: documentation

#20 Implements Mailing System with Handlebars Templates
  package-lock.json
  package.json
  src/infra/email/messages/sendStudentQRCodeEmail.js
  src/infra/email/nodemailer.js
  src/infra/email/views/sendStudentQRCodeEmail.js
  src/infra/email/views/studentQRCodeEmail.handlebars
  src/utils/generateStudentQRCode.js
Labels: enhancement

#23 Automagically send email on student creation
  src/controllers/StudentController.js
Labels: enhancement

#24 docs: improve docs and fix ui bugs
  docs/index.html
  docs/swagger.yaml
Labels: bug, documentation, enhancement

#27 Standardize error sending via sendStatus()
  package-lock.json
  package.json
  src/server.js
  src/utils/sendStatusJSONFormatter.js
Labels: enhancement

#28 docs: add new error standard
  docs/swagger.yaml
Labels: documentation

#29 Add seed for database with default user
  .env.template
  package.json
  prisma/seed.js
Labels: bug

#30 imports and exports linting
  .eslintrc.json
  package-lock.json
  package.json
  src/PrismaClient.js
  src/controllers/OauthController.js
  src/controllers/StudentController.js
  src/controllers/UserController.js
  src/infra/email/messages/sendStudentQRCodeEmail.js
  src/infra/email/nodemailer.js
  src/routes/oauth.js
  src/routes/students.js
  src/routes/users.js
  src/server.js
  src/services/OauthService.js
  src/services/StudentService.js
  src/services/UserService.js
  src/utils/generateStudentQRCode.js
Labels: linting

#32 Add student meal validation
  prisma/ERD.svg
  prisma/migrations/20230223184526_add_meals_tables/migration.sql
  prisma/migrations/20230223214331_fix_deletion/migration.sql
  prisma/migrations/20230223232239_add_constraint_session_student/migration.sql
  prisma/migrations/20230224230728_change_students_meal_sessions_fields_names/migration.sql
  prisma/migrations/20230224231004_rename_student_in_meal_session_relation_fields_names/migration.sql
  prisma/schema.prisma
  src/controllers/MealSessionController.js
  src/controllers/OauthController.js
  src/controllers/StudentController.js
  src/controllers/UserController.js
  src/errors/EntryExists.js
  src/errors/InvalidPassword.js
  src/errors/MealSession/MealSessionFinished.js
  src/errors/MealSession/MealSessionNotFound.js
  src/errors/MealSession/StudentAlreadyInMealSession.js
  src/errors/StudentNotFound.js
  src/errors/oAuth/InvalidPassword.js
  src/infra/email/nodemailer.js
  src/routes/mealSessions.js
  src/routes/students.js
  src/routes/users.js
  src/server.js
  src/services/MealSessionService.js
  src/services/OauthService.js
  src/services/StudentService.js
  src/services/UserService.js
Labels: enhancement
